tunnel: 5be6c96b-0b5f-4fd5-8e9b-49dc431a9471
credentials-file: C:\Users\CAMARAS06\.cloudflared\5be6c96b-0b5f-4fd5-8e9b-49dc431a9471.json

protocol: http2

ingress:
  - hostname: comialex.work
    service: http://127.0.0.1:4201
   
  - service: http_status:404